### ISSUE TITLE
[FEATURE] Extension for VSCode

### ISSUE THREAD

**Issue by saschabrockel** [jordan-dalby/ByteStash#149] opened 2024-12-05 09:22 UTC
**Is your feature request related to a problem? Please describe.**
No, it is no problem but an idea.

**Describe the solution you'd like**
There are tools like MassCode (https://github.com/massCodeIO/massCode) available that only run locally and can be integrated into VSCode for example. It would be very awesome to have all your code snippets right in VSCode with your own hosted instance of ByteStash. MassCode is open-source as well. Maybe the code of the extension creation can be reused in parts.

**Describe alternatives you've considered**
Not sure how to do in another way.

**Comment by jordan-dalby** [comment] 2024-12-05 10:10
Dupe of #47 good idea though!

**Closed by jordan-dalby** 2024-12-05 10:10 UTC
Labels: enhancement
